services:
  jenkins:
    container_name: jenkins_gist
    image: jenkins/jenkins:latest
    ports:
      - "8081:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - gits_net
    user: root
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y docker.io && /usr/local/bin/jenkins.sh"
networks:
  gits_net: